const MIN_PRICE = 100;
const MAX_PRICE = 100000;

const FIRST_WEEK_DAY = 1;
const LAST_WEEK_DAY = 7;

const FIRST_INDEX = 1;
const LAST_INDEX = 100;

const NUMBER_OF_PHOTOS = 6;

const MIN_RATING = 1;
const MAX_RATING = 5;
const RATING_DECIMAL_NUMBERS_COUNT = 1;

const MIN_ROOMS_COUNT = 1;
const MAX_ROOMS_COUNT = 8;

const MIN_ADULTS = 1;
const MAX_ADULTS = 10;

const MIN_COMMENTS = 0;
const MAX_COMMENTS = 100;

export {
  FIRST_INDEX, FIRST_WEEK_DAY, LAST_INDEX, LAST_WEEK_DAY, MAX_ADULTS, MAX_COMMENTS, MAX_PRICE, MAX_RATING,
  MAX_ROOMS_COUNT, MIN_ADULTS, MIN_COMMENTS, MIN_PRICE, MIN_RATING, MIN_ROOMS_COUNT, NUMBER_OF_PHOTOS, RATING_DECIMAL_NUMBERS_COUNT
};
