# Категории
## Получить список категорий
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@mail.ru",
  "avatar": "default-avatar.png",
  "password": "123456",
  "userType": "Pro"
}

###

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "ivnikon@mail.ru",
  "password": "12345"
}

###
## Отправить изображение

POST http://localhost:5000/users/666b4668456811eab6efd82a/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /home/ivnikon/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
