# Категории
## Получить список категорий
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "ivnikon",
  "email": "ivnikon@mail.ru",
  "avatar": "default-avatar.png",
  "password": "12345",
  "userType": "Pro",
  "favorites": []
}

###

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "ivnikon@mail.ru",
  "password": "12345"
}

###
